spring:
  application:
    name: automationlab-be
  
  data:
    mongodb:
      host: localhost
      port: 27017
      database: automationlab
      auto-index-creation: false
  
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

# File upload configuration
file:
  upload-dir: objectTemplate

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    com.automationlab.be: DEBUG
    org.springframework.data.mongodb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  info:
    title: Aubotmation Lab Backend API
    description: Backend service for Aubotmation Lab with MongoDB
    version: 1.0.0
    contact:
      name: Aubotmation Lab Team
      email: support@automationlab.com
  packages-to-scan: com.automationlab.be.controller
