spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:aubotmationlab}
      username: ${MONGODB_USERNAME:}
      password: ${MONGODB_PASSWORD:}

logging:
  level:
    com.aubotmationlab.be: INFO
    org.springframework.data.mongodb: WARN
    org.springframework.web: WARN
