spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: aubotmationlab_dev

logging:
  level:
    com.aubotmationlab.be: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.web: DEBUG
