spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: automationlab

logging:
  level:
    com.automationlab.be: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.web: DEBUG
